defmodule Ming.Context do
  @moduledoc """
  Execution context shared across middleware and handlers.

  It carries request data, routing information, optional metadata, and the
  eventual response generated by the pipeline.
  """

  @type t :: %__MODULE__{}

  @enforce_keys [:request, :routing_key, :timeout]

  defstruct [
    :id,
    :correlation_id,
    :handler,
    :metadata,
    :request,
    :response,
    :routing_key,
    :timeout,
    :timestamp,
    assigns: %{},
    halted?: false,
    middlewares: []
  ]

  @doc """
  Stores a value in the context assigns map.
  """
  def assign(%__MODULE__{assigns: assigns} = context, key, value),
    do: %__MODULE__{context | assigns: Map.put(assigns, key, value)}

  @doc """
  Returns whether pipeline execution has been halted.
  """
  def halted?(%__MODULE__{halted?: halted?}), do: halted?

  @doc """
  Halts pipeline execution for this context.
  """
  def halt(%__MODULE__{halted?: false} = context), do: %__MODULE__{context | halted?: true}
  def halt(%__MODULE__{} = context), do: context

  @doc """
  Extracts the current response from context.
  """
  def response(%__MODULE__{response: response}), do: response

  @doc """
  Sets a response in the context.
  """
  def respond(%__MODULE__{} = context, respond), do: %__MODULE__{context | response: respond}
end
