defmodule Ming.Context do
  @moduledoc """
  Execution context shared across middleware and handlers.

  It carries request data, routing information, optional metadata, and the
  eventual response generated by the pipeline. Middleware short-circuits
  the pipeline by not calling `next`, so there is no halt flag — see
  `Ming.Middleware`.
  """

  @type t :: %__MODULE__{
          id: any(),
          correlation_id: any(),
          metadata: map() | nil,
          request: any(),
          response: any() | nil,
          routing_key: Ming.routing_key(),
          timeout: timeout(),
          timestamp: DateTime.t() | nil,
          assigns: map()
        }

  @enforce_keys [:request, :routing_key, :timeout]

  defstruct [
    :id,
    :correlation_id,
    :metadata,
    :request,
    :response,
    :routing_key,
    :timeout,
    :timestamp,
    assigns: %{}
  ]

  @doc """
  Stores a value in the context assigns map.
  """
  @spec assign(t(), atom(), any()) :: t()
  def assign(%__MODULE__{assigns: assigns} = context, key, value),
    do: %__MODULE__{context | assigns: Map.put(assigns, key, value)}

  @doc """
  Extracts the current response from context.
  """
  @spec response(t()) :: any()
  def response(%__MODULE__{response: response}), do: response

  @doc """
  Sets a response in the context.
  """
  @spec respond(t(), any()) :: t()
  def respond(%__MODULE__{} = context, response), do: %__MODULE__{context | response: response}
end
